spring:
  application:
    name: mini-github

  datasource:
    url: jdbc:postgresql://localhost:5432/mini_github_db
    username: mg_user
    password: mg_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  graphql:
    graphiql:
      enabled: true